<?php

namespace App\Models;

use App\Enums\PointType;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{
    use HasFactory;

    protected $fillable = [
        "question_id",
        "option_id",
        "point"
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::created(function($model){
            // 정답이라면
            if($model->option->correct) {
                $model->update(["point" => PointType::$points[PointType::QUIZ_CORRECT] ]);

                $model->user->pointHistories()->create([
                    "type" => PointType::QUIZ_CORRECT,
                    "point" => PointType::$points[PointType::QUIZ_CORRECT],
                ]);
            }
        });

        self::updating(function($model){
            if($model->count_view != $model->getOriginal("count_view")){
                if($model->count_view == 1)
                    $model->user->pointHistories()->create([
                        "type" => PointType::QUIZ_SHARE,
                        "point" => PointType::$points[PointType::QUIZ_SHARE]
                    ]);
            }
        });
    }

    public function question()
    {
        return $this->belongsTo(Question::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function option()
    {
        return $this->belongsTo(Option::class);
    }
}
