<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Newspaper extends Model
{
    use HasFactory;

    protected $fillable = [
        "curation_id",
        "title",
        "description",
        "url",
        "img_url",
        "order",
        "category"
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function($model){
            $model->order = $model->curation->newspapers()->count() + 1;
        });
    }

    public function curation()
    {
        return $this->belongsTo(Curation::class);
    }
}

