<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class PointHistory extends Model
{
    use HasFactory;

    protected $fillable = [
        "user_id",
        "type",
        "point",
        "category",
        "read_history_id"
    ];

    protected static $levelUpPoint = 50;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::created(function($model){
            $point = $model->user->point + $model->point;

            if($point >= self::$levelUpPoint){
                $leavePoint = $point - self::$levelUpPoint;

                $model->user->update([
                    "level" => $model->user->level + 1,
                    "point" => $leavePoint
                ]);
            }else{
                $model->user->update([
                    "point" => $model->user->point + $model->point
                ]);
            }
        });
    }

    public static function getLevelUpPoint()
    {
        return self::$levelUpPoint;
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function readHistory()
    {
        return $this->belongsTo(ReadHistory::class);
    }
}
